language: python
python:
  - "2.7"
before_install:
  - export DJANGO_SETTINGS_MODULE="app.settings_tests"
install:
  - pip install --use-mirrors -r tests_requirements.txt
  - pip install --use-mirrors coveralls
  - python ./manage.py syncdb --pythonpath=. --noinput
matrix:
  allow_failures:
script:
  - coverage run --source=app ./manage.py test app.core app.api --settings=app.settings_tests
after_success:
  - coveralls
