language: python
python:
  - "2.7"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - xargs -a npm_requirements.txt npm install -g
  - export DJANGO_SETTINGS_MODULE="app.settings_tests"
install:
  - pip install --use-mirrors -r requirements.txt
  - pip install --use-mirrors coveralls
  - python ./manage.py syncdb --pythonpath=. --noinput
matrix:
  allow_failures:
script:
  - coverage run --omit=app/core/migrations/ --source=app ./manage.py test --settings=app.settings_tests
  - karma start --single-run --browsers PhantomJS
after_success:
  - coveralls
